title: "IST 110 Learning Portfolio"
description: "Digital showcase of my assignments, projects, and reflections from IST 110."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Site navigation – order matters
navigation:
  - title: "Home"
    url: /
  - title: "Assignments"
    url: /assignments/
  - title: "Projects"
    url: /projects/
  - title: "Skills"
    url: /skills/
  - title: "Contact"
    url: /contact/